apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAQFTZn64QeoHwAAinkz62U4KADVkL9EoqMsWCHD46TOVcFXu/CQ4Ln7hoAbWFg/ab2sSyTygk+MpG8xxwvUI8DSm9/ghruLMpMlA0vHZG2GB2krYkeS5JO6ULsChKevjXhij2+DDusIAj1GDiS59bPaa/KizR8ppQPlfs1CS3/Q1ftTkTbUUfAVUwH/7FEvIQSNm+/2HEn3RWGR1MvHYNUKuUfYwDqdMcox2RYoTywD0jnRaXAxfqNBwq2JNdMAsDqX3LFtBzjd9wLiao0HLHQ6dqDl36WGwRQEEbVlRLdee7zgWeQix+iAXBWuvTJ2BwhonbFFP4nTWW1j0KcUZ4DsXDdT6NzypLahXBK55RI+m8EcJYiq/WjpaDTAtcrSVq/7mkoK27qCwtKTFBHAYv9ZxuB5lEVvDiYjmR/1NJNn1cts5ouZ5ECJPHl+IjIS6xVxTEKIGPPALfiC/IFvtcG5CK/MJSMp2Ac5p16lqYdhe9joWuTu2oAOfmL5bgysGrSoy/fkCjlxJhNKW5AF0ERVBNxfHFM4O295Z1WaxtqiQNSbgodmBM4cECR0XxpAWdu5p8/5jXWOseiiZsqm8GSdYBwLhib1G67AJb7wSO3G6kxS+DIQLi0VLN/zqp+IVnoX5HlkgYo0kKQPhhBH+37FE4oMQnajbmLlDJRMUVFvZmMo6ZTCI/2BQSmYViva7c1PwCyMLTFad609DeqxD2VowN322ZvGaypdDn26t+M9tiyWhXfrAny
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

